name: Check Published

on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * *'

jobs:
  checkPublished:
    runs-on: ubuntu-latest
    name: Check Published
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Check Published
        uses: checkdigit/github-actions/check-published@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          DEBUG: '*'
          SLACK_PUBLISH_MISMATCH: ${{ secrets.SLACK_PUBLISH_MISMATCH }}
